version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - amirthavalliG
  versioning-strategy: increase
  ignore:
  - dependency-name: karma
    versions:
    - 6.0.4
  - dependency-name: "@ui5/cli"
    versions:
    - 2.9.1
