language: java

cache:
  npm: true
  directories:
    - $HOME/.m2
os:
 - linux

services:
 - docker

jdk:
 - openjdk8

node_js:
 - "10.15.1"

install: "npm install"

jobs:
  include:
    - stage: "JSLint Checks"
      script: "npm run lint"
    - stage: "QUnit / QUnit Integration / OPA5 Tests"
      script: "npm run test-mockserver"

notifications:
  email:
    on_failure: always
    on_success: change
