language: java

cache:
  directories:
    - $HOME/.m2

os:
 - linux

services:
 - docker

jdk:
 - openjdk8

install: npm install

branches:
  only:
    - master

jobs:
  include:
    - stage: "JSLint Checks"
      script: npm run lint
    - stage: "QUnit / QUnit Integration / OPA5 Tests"
      script: npm run test-mockserver
    - stage: "Generate API Documentation"
      if: (branch = master) AND (NOT (type = pull_request))
      script: "npm run docs"
      deploy:
        local-dir: generated_docs/html
        provider: pages
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        skip-cleanup: true
        keep-history: true
        on:
          branch: master

notifications:
  email:
    on_failure: always
    on_success: change