language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
os:
 - linux

services:
 - docker

jdk:
 - openjdk8

node_js:
 - "12"

install:
- npm i -g npm
- npm ci

jobs:
  include:
    - stage: "JSLint Checks"
      script: npm run lint
    - stage: "QUnit / QUnit Integration / OPA5 Tests"
      script: npm run test-mockserver

notifications:
  email:
    on_failure: always
    on_success: change
