language: java

cache:
  directories:
    - $HOME/.m2

os:
 - linux

services:
 - docker

jdk:
 - openjdk8

install: npm install

branches:
  only:
    - master

jobs:
  include:
    - stage: "Checks and Tests"
      name: "JSLint Checks"
      script: npm run lint
    - script: npm run test-mockserver && npm run deploy:coverage
      name: "QUnit / QUnit Integration / OPA5 Tests"
    - stage: "Release"
      name: "Generate a new Release"
      if: (branch = master) AND (NOT (type = pull_request))
      script: echo \"Skipping second test execution but keep NPM hooks alive.\"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: "Generate API Documentation"
      if: (branch = master) AND (NOT (type = pull_request))
      script: "npm run docs"
      deploy:
        local-dir: generated_docs/html
        provider: pages
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
        on:
          branch: master

notifications:
  email:
    on_failure: always
    on_success: change
  webhooks: https://coveralls.io/webhook