name: Checks and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  jslint:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Install
        run: npm install
      - name: JSLint Checks
        run: npm run lint